### ISSUE TITLE
The content of About section on Home page goes on the overlay

### ISSUE THREAD

**Issue by miyabitanimchi** [shiv-chan/senpai-kohai#32]
I noticed the content doesn't go under the overlay.
To solve this I think we can just put or change values of z-index of the content and some elements around it.

<img width="976" alt="スクリーンショット 2021-12-13 午後11 44 52" src="https://user-images.githubusercontent.com/69213541/145957069-cb6c940e-1113-4c0f-8060-3fece47bc603.png">

**Comment by shiv-chan** [comment]
solved! 👍
